//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace otopark_otomasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class kayit
    {
        public int KayitId { get; set; }
        public string plaka { get; set; }
        public string SahipAdı { get; set; }
        public string SahipSoyadı { get; set; }
        public string marka { get; set; }
        public string model { get; set; }
        public string ParkAlan { get; set; }
        public string AracYıkama { get; set; }
        public Nullable<System.DateTime> GirisSaati { get; set; }
        public Nullable<System.DateTime> CıkısSaati { get; set; }
        public Nullable<int> fiyat { get; set; }
        public Nullable<int> Durum { get; set; }
        public Nullable<int> ParkYeriId { get; set; }
    
        public virtual parkyeri parkyeri { get; set; }
    }
}
